### ISSUE TITLE
Add support for request authentication

### ISSUE THREAD

**Issue by narendravaghela** [multidots/cakephp-rest-api#1]
Implement support of authentication of API request by using JSON Web Tokens (https://github.com/firebase/php-jwt)

**Comment by narendravaghela** [comment]
Implemented!

**Comment by anupalusoft** [comment]
When doing a test with login the same way you suggested its giving the error
`"error": "Invalid or empty token."`
Is the token is required for very initial login attempt? Can you send a screenshot of Postman extension?

**Comment by narendravaghela** [comment]
Please read this tutorial - http://blog.narendravaghela.com/cakephp-build-rest-apis-with-restapi-plugin-part-2/
You have to disable token check for your login route.

**Comment by anupalusoft** [comment]
Ok sorry about that. How do i enable the debugging mode for this plugin. 
It not showing exception instead giving Internal Server Error. 
P.S. there should enable disable in config.

**Comment by narendravaghela** [comment]
Thanks for suggestion. Will implement that in next release.

**Comment by anupalusoft** [comment]
Still not able to resolve the "Internal Server Error" Not able to catch the exception. 
Any help please?

**Comment by narendravaghela** [comment]
Try to use dev-master varsion of the plugin, it has now exception message in response instead of Internal Server Error.
