### ISSUE TITLE
Configure Log

### ISSUE THREAD

**Issue by pablogupi** [multidots/cakephp-rest-api#11]
Hi
I would like to specify that is saved in the log. For example my app generated a lot of request_data and I prefer not to save it in the database if there is no error. Thanks

**Comment by narendravaghela** [comment]
Yeah, we can modify the logging feature and add more options to manage the logs. If you have an idea, you can make a PR or I will check it in weekend.

**Comment by scargoll** [comment]
Hi,
An option very usefull for the logs is to allow us to choose which IP to log : my app is behind a proxy server, so in the log i have the IP of this proxy, it would be better if we can use 'http_x_forwarded_for' for logging.
Thanks.

**Comment by narendravaghela** [comment]
Implemented!
