### ISSUE TITLE
Route scope

### ISSUE THREAD

**Issue by SamYan** [multidots/cakephp-rest-api#12]
Hi, i'm using your plugin and get a little problem.

my router config:

```
    Router::scope('/api/*', function ($routes) {
            
        $routes->connect('/', ['controller' => 'Eeccs', 'action' => 'index', 'allowWithoutToken' => true]);
        $routes->connect('add/', ['controller' => 'Eeccs', 'action' => 'add', 'allowWithoutToken' => true]);
    });

```
When i access  to index action its ok but when i try to access to add action i get the same result of index action. What's wrong, tell me please.

Thanks in advance

**Comment by SamYan** [comment]
I was thinking that the wrong its your plugin but not.

Solution:


`Router::scope('/api', function ($routes) {
        
    $routes->connect('/', ['controller' => 'Eeccs', 'action' => 'index', 'allowWithoutToken' => true]);
    $routes->connect('/add/', ['controller' => 'Eeccs', 'action' => 'add', 'allowWithoutToken' => true]);
});
`
Thanks

**Comment by narendravaghela** [comment]
Great :)
