### ISSUE TITLE
Basic Form Authentication Stopped working

### ISSUE THREAD

**Issue by durgadutt87** [multidots/cakephp-rest-api#13]
While loading this plugin in bootstrap.php, Basic Form authentication stops working.

**Comment by narendravaghela** [comment]
@durgadutt87 
Can you share more details on this? Also, few code samples will be more helpful to check this issue.

**Comment by durgadutt87** [comment]
Thanks for getting back to me. Here are the details:
Rule in routes.php :   /*
    $routes->connect('/api/login', ['controller' => 'RestLogin','action' => 'index', 'allowWithoutToken' => true]);

AppController is used for non Rest calls. Here is the initialise function:
public function initialize()
    {
        parent::initialize();
        
        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');

        /*
         * Enable the following components for recommended CakePHP security settings.
         * see http://book.cakephp.org/3.0/en/controllers/components/security.html
         */
        $this->loadComponent('Crud.Crud', [
            'actions' => [
                'Crud.Index',
                'Crud.View',
                'Crud.Add',
                'Crud.Edit',
                'Crud.Delete'
            ],
            'listeners' => [
                'Crud.Api',
                'Crud.ApiPagination',
                'Crud.ApiQueryLog'
            ]
        ]);
        if(!$this->request->is('json'))
        { 
             $this->loadComponent('Auth', [
            'loginAction' => [
                'controller' => 'login',
                'action' => 'index'
            ],
            'logoutAction' => [
                'controller' => 'Pages',
                'action' => 'display',
                'home'
            ],
            'loginRedirect'=>[
                'controller'=>'Users',
                'action'=>'index'
            ],
            'authorize' => array('Controller')
            ]);
        }
    }
    

I using above Auth configuration for my admin form login:

class LoginController extends AppController
{
    public $helpers = array('Froala.Froala');
    
    public function initialize()
    {
         parent::initialize();
         $this->viewBuilder()->layout('Admin/home');
         $this->loadComponent('Flash');
         $this->Auth->allow(['index','logout']);
    }

    
    public function index()
    {  
        if($this->request->is('post'))
        {    
            $user = $this->Auth->identify();
            if ($user) {
                $this->Auth->setUser($user);
                return $this->redirect($this->Auth->redirectUrl());
            }
            $this->Flash->error(__('Invalid username or password, try again'));
        }
         
        
    }
    
    public function logout()
    {
        $this->Auth->logout();
        return $this->redirect($this->Auth->logout());
    } 
}

Unfortunately it keep sending me authentication error when your plugin is loading. Once I comment loading, My forms starts working. 

I am not sure if I am missing anything as I am new to cake.

**Comment by narendravaghela** [comment]
There was an issue, `AppController::initialize()` method was being called twice. Can you please check with the latest release of plugin?
