### ISSUE TITLE
AppController::initialize called twice with plugin enabled?

### ISSUE THREAD

**Issue by wilsmex** [multidots/cakephp-rest-api#15]
When I load the plugin in my bootstrap file via: 
`Plugin::load('RestApi', ['bootstrap' => true]);`

My initialize() function in my AppController is being called twice.  If I set `bootstrap => false`
initialize() is only called once.

Is this normal behavior?

**Comment by narendravaghela** [comment]
Hi @wilsmex,
Our plugin has its own `AppController`, so it is possible that the `initialize()` is being called twice.
Are you facing any issue due to this behavior?
Regarding `'bootstrap' => true` option, it is required to make the plugin work in the correct way.

**Comment by narendravaghela** [comment]
Hi @wilsmex 
This is resolved in new release.
