### ISSUE TITLE
Allow more flexible response types (per-method)

### ISSUE THREAD

**Issue by mikerogerz** [multidots/cakephp-rest-api#16]
In my API, I have a method to download a pdf file via a GET, which for now is forced to automatically download the file, avoiding the json responseType (which works fine). If I don't force the download though, the response is always json, even when attempting to force the response mimetype as application/pdf.

Any ideas?

**Comment by narendravaghela** [comment]
The plugin currently supports only json and xml response types. If your controller extends the ApiController, the response will be generated with application/json header only.

We can think of your requirement as a new feature. If you have any solution in mind, you can discuss here.

**Comment by mikerogerz** [comment]
#18 works in my case, but let me know if you have a better solution. Thanks.

**Comment by narendravaghela** [comment]
Thanks @mikerogerz we will check and get back to you.

**Comment by narendravaghela** [comment]
Please check this PR for details - https://github.com/multidots/cakephp-rest-api/pull/18
