### ISSUE TITLE
Add support to log request/response data

### ISSUE THREAD

**Issue by narendravaghela** [multidots/cakephp-rest-api#2]

**Comment by narendravaghela** [comment]
Implemented!

**Comment by anupalusoft** [comment]
Hi,
It is not saving log in api_requests table. Am working on with MS SQL server db.

**Comment by narendravaghela** [comment]
Did you create a table in your database? Does your cake app able to connect to database? Does your database user have permission to write into table?

**Comment by anupalusoft** [comment]
Yes all are fine.

**Comment by narendravaghela** [comment]
Have you enabled request logging? See https://github.com/multidots/cakephp-rest-api#log-request--response

**Comment by anupalusoft** [comment]
Yes I did.

**Comment by narendravaghela** [comment]
Okay, try to debug this file and see what happens - `\RestApi\Utility\ApiRequestLogger::log()`
Do you see any exception there? Try to write log using `\Cake\Log\Log::debug($e);` in catch part.

**Comment by anupalusoft** [comment]
Where do that 'accessToken' will come from configurations ?
'token' => Configure::read('accessToken'), 
We aren't defining it anywhere. By the way no exception i found. 

P.S am using it without allowWithoutToken => true

**Comment by narendravaghela** [comment]
It is automatically defined by plugin.
I have never tried this with MS SQL database. I trust on CakePHP ORM that it works well with MS SQL ;)

**Comment by anupalusoft** [comment]
Ok i got the exception. Cannot insert the value NULL into column 'id'.
You skipped to give AUTO_INCREMENT in table definition.

**Comment by narendravaghela** [comment]
Actually, that is not the case. Primary key is not integer, it is uuid and that is char(36) or binary(36).

**Comment by anupalusoft** [comment]
Ok but this is the exception is giving
`Cannot insert the value NULL into column 'id', table 'api_requests'; column does not allow nulls. INSERT fails.'`

**Comment by anupalusoft** [comment]
After setting to Auto increment its working fine now.

**Comment by narendravaghela** [comment]
Great, I will check this with CakePHP ORM as well.
