### ISSUE TITLE
404 response in JSON

### ISSUE THREAD

**Issue by klorant5** [multidots/cakephp-rest-api#24]
Hi.
I use your plugin and it work well but I ran into a problem.
I would like to set the response format for the 404 error page to JSON.

I have something like this:
```php
Router::scope('/api/v1', function (RouteBuilder $routes) {
    
    $routes->setExtensions(['json']);
    //here come the configs of the routes
    //for example: $routes->get('/ping', ['controller' => 'ApiController', 'action' => 'ping']);
    //...

});
```
If I call the `[testdomain]/api/v1/asdasd` url the application throws a 404 error because `asdasd` is not existing in the config of my routes and it's response is in html format, but I want a JSON response.

Is there a way to set JSON response to all of the error messages in the `api/v1` scope?

**Comment by narendravaghela** [comment]
You can create a global route for all you unmatched URLs.

```php
Router::scope('/api/v1', function (RouteBuilder $routes) {
    
    $routes->setExtensions(['json']);
    //here come the configs of the routes
    //for example: $routes->get('/ping', ['controller' => 'ApiController', 'action' => 'ping']);
    //...
    $routes->connect('/*', ['controller' => 'Pages', 'action' => 'notFound']);
});
```

And return json response in the `PagesController::notFound` action.

Make sure you add this route at the last place.

**Comment by klorant5** [comment]
Thank you for the answer. It works!
