### ISSUE TITLE
Not installing with firebase/php-jwt 5

### ISSUE THREAD

**Issue by anuj9196** [multidots/cakephp-rest-api#27]
I have `firebase/php-jwt 5.0.0` installed. But when try to install the plugin
```
composer require multidots/cakephp-rest-api
```
it gives error as
```
Problem 1
    - Installation request for firebase/php-jwt (locked at v5.0.0) -> satisfiable by firebase/php-jwt[v5.0.0].
    - multidots/cakephp-rest-api v1.1.0 requires firebase/php-jwt ^4.0 -> satisfiable by firebase/php-jwt[v4.0.0].
    - multidots/cakephp-rest-api v1.1.1 requires firebase/php-jwt ^4.0 -> satisfiable by firebase/php-jwt[v4.0.0].
    - Conclusion: don't install firebase/php-jwt v4.0.0
    - Installation request for multidots/cakephp-rest-api ^1.1 -> satisfiable by multidots/cakephp-rest-api[v1.1.0, v1.1.1].

```

**Comment by narendravaghela** [comment]
Thanks for the report. It seems the plugin dependency needs to be updated.

**Comment by anuj9196** [comment]
Thanks @narendravaghela , Hope it will be updated shortly. I need to add this plugin to my application ASAP.

**Comment by narendravaghela** [comment]
Till then, you can download the zip file of this plugin and place it in your plugins directory, and update the compose.json with new version of jwt package.

**Comment by anuj9196** [comment]
I did it, and now the package version are
```
multidots/cakephp-rest-api            v1.1.0 
firebase/php-jwt                             v4.0.0 
```

But, when It is not generating token. I'm using
```
public function token() {
    $payload = ['app_id' => $this->userApp->id, 'user_id' => $this->user->id];
    debug($payload);                                              // printing this
    $token = JwtToken::generateToken($payload);
    debug('token');                                                 // not printing, unreachable
    debug($token);                                                // not printing, unreachable
}
```
The `debug($payload)` produce
```
[
	'app_id' => '37a2b3d7-347a-4350-8af2-0fafda542f52',
	'user_id' => 'a5c13fc8-5e84-4cc1-9bb2-b489a073f37c'
]
```

Even there is no error message and any code below `JwtToken::` is unreachable

**Comment by narendravaghela** [comment]
- Did you add `use RestApi\Utility\JwtToken;` on top of your file?
- Please check `APP/logs/error.log` for any possible error as well as your apache/nginx error log to see what is going wrong.

**Comment by anuj9196** [comment]
Yes, I have added `use RestApi\Utility\JwtToken;`. Also, there is no relevant log in `/logs/error.log` file

**Comment by narendravaghela** [comment]
What is the output? Did you check your server's error log?

**Comment by anuj9196** [comment]
Found the error 
```
Algorithm not supported
```

**Comment by narendravaghela** [comment]
Great, please use valid algorithm name then :)

**Comment by anuj9196** [comment]
Thanks, narendravaghela, I checked config file and there was some typo mistake that was there accidentally because I had copied the config from my another application which is using this plugin and was working there.
