### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by yusser** [multidots/cakephp-rest-api#28]
Hi, the site is down.

http://blog.narendravaghela.com/cakephp-build-rest-apis-with-restapi-plugin-part-1/

There is a way to see the tutorial?

**Comment by narendravaghela** [comment]
Hi @yusser,
Actually, my hosting is expired :) I have a backup of the tutorial and will post it on medium soon and update the link.

**Comment by narendravaghela** [comment]
Meanwhile, you can follow the steps in README file of the repo.

**Comment by yusser** [comment]
I follwed this steps and it worked. But, if i'm sure, the tutorial is more complete. 

I'm using AuthComponent identify the user to generate a token. But, when i activete AuthComponent all my routes returns Not Allowed. I think the middleware in plugin solve it retriving the user by JWT Token. 

I don't know if i saw that in tutorial.

**Comment by yusser** [comment]
I got it. I have to implement authenticate's logic on beforeFilter method. Because, payload's data is only available there, ok?

**Comment by narendravaghela** [comment]
Yes, that's correct.

**Comment by zhunt** [comment]
WayBack Machine has copies:

https://web.archive.org/web/20170724055022/http://blog.narendravaghela.com/cakephp-build-rest-apis-with-restapi-plugin-part-1/

https://web.archive.org/web/20170729150712/http://blog.narendravaghela.com:80/cakephp-build-rest-apis-with-restapi-plugin-part-2

**Comment by narendravaghela** [comment]
@zhunt Thanks, man. I will copy it out on my medium and update the readme.

**Comment by narendravaghela** [comment]
Here is the updated link to tutorial - https://medium.com/@narendravaghela/cakephp-build-rest-apis-with-restapi-plugin-1-c55b73fb9c0

**Comment by PhantomWatson** [comment]
Could you update the link in the README file? It's still broken.

**Comment by narendravaghela** [comment]
@PhantomWatson 
I don't have access to repo now. Try this simple alternative https://github.com/sprintcube/cakephp-rest if you want!
