### ISSUE TITLE
Auth->allow(); error due to not extending AppController

### ISSUE THREAD

**Issue by anupalusoft** [multidots/cakephp-rest-api#3]
You did it with extending ApiController 
so how do we access the Auth and other Components ?

**Comment by narendravaghela** [comment]
You can add your components in your controller's `initialize()` method.
Also, for authentication, this plugin provides a support of JWT tokens - https://github.com/multidots/cakephp-rest-api#request-authentication-using-jwt

**Comment by narendravaghela** [comment]
See example below.
```php
<?php

namespace App\Controller;

use RestApi\Controller\ApiController;

/**
 * Foo Controller
 *
 */
class FooController extends ApiController
{

    public function initialize()
    {
        parent::initialize();
        $this->loadComponent('Auth');
    }

    /**
     * bar method
     *
     * @return Response|null
     */
    public function bar()
    {
        // movie list
        $movies = [
            'Captain America: Civil War',
            'The Wave',
            'Deadpool'
        ];

        $this->apiResponse['movies'] = $movies;
    }
}
```

**Comment by anupalusoft** [comment]
Ok Working, But i am still not able to access the method allowed without token. 
Is is really required to use Token to test it even. ?

**Comment by narendravaghela** [comment]
No, token is not required. You can bypass the token check by setting `allowWithoutToken` parameter in your route.
```php
$routes->connect('/demo/foo', ['controller' => 'Demo', 'action' => 'foo', 'allowWithoutToken' => false]);
```
