### ISSUE TITLE
Exceptions are not being handled

### ISSUE THREAD

**Issue by brunoserra** [multidots/cakephp-rest-api#6]
First, thank you for creating such a handful plugin :)

The responses are working just fine, but not when it comes to exceptions. I've tried to set the exceptionRenderer in my app.php file to RestApi\Error\ApiExceptionRenderer with no luck (I don't know what else to try).

Here's my api.php config file:

```php
<?php
    return [
        'ApiRequest' => [
            'debug' => true,
            'responseFormat' => [
                'statusKey' => 'status',
                'statusOkText' => 'success',
                'statusNokText' => 'fail',
                'resultKey' => 'results',
                'messageKey' => 'message',
                'defaultMessageText' => 'Empty response!',
                'errorKey' => 'error',
                'defaultErrorText' => 'Unknown request!'
            ],
            'log' => false,
            'jwtAuth' => [
                'enabled' => false,
                // 'cypherKey' => 'R1a#2%dY2fX@3g8r5&s4Kf6*sd(5dHs!5gD4s',
                // 'tokenAlgorithm' => 'HS256'
            ],
            'cors' => [
                'enabled' => false,
                // 'origin' => '*',
                // 'allowedMethods' => ['GET', 'POST', 'OPTIONS'],
                // 'allowedHeaders' => ['Content-Type, Authorization, Accept, Origin'],
                // 'maxAge' => 2628000
            ]
        ]
    ];
```

What could that be? 
Thanks again!

**Comment by narendravaghela** [comment]
You don't need to set the exception renderer explicitly.

What exactly does it return instead of exception message? Is your controller extending RestApi\ApiController?

Please let me know a little bit more details and I will be happy to help.

**Comment by brunoserra** [comment]
Sure! Yes it is extending (and It works until I throw a new exception):

**AppController.php**
```
<?php
namespace App\Controller\Api;
use RestApi\Controller\ApiController;
use Cake\Event\Event;

use \Crud\Controller\ControllerTrait;
use Cake\Controller\Component\AuthComponent;
use Cake\Network\Exception\UnauthorizedException;

class AppController extends ApiController {
...
```

**UsersController.php**
```
<?php
namespace App\Controller\Api;
use App\Controller\Api\AppController;

class UsersController extends AppController {
   
    public function index () {
        throw new Exception(__('Invalid or missing user_id for token generation'));
    }
...
```

The expected result would be:
```
{
	"status":"fail",
	"results":{
		"message":"Invalid or missing user_id for token generation"
	}
}
```

But instead I'm getting cake's regular response:
```
{
  "message": "Invalid or missing user_id for token generation",
  "url": "/api/users/index",
  "code": 500
}
```

**Comment by narendravaghela** [comment]
Thanks for the details!
I will look into this and get back to you soon.

**Comment by romanklco** [comment]
Found a bug where wrong variable was set on RestApiMiddleware class (line 38). Instead of $this->renderer, $this->expcetionRenderer must be set. Maybe a cakephp 3.x version update.

**Comment by narendravaghela** [comment]
@brunoserra This might be due to a new release of Cake 3.4. I have tested the stable version with latest Cake 3.3.x  and it is working.
To make this compatible with 3.4, we have to make some changes as @romanklco explained.
Please let me know if it still does not work for you.

**Comment by narendravaghela** [comment]
Fixed in new release!
