### ISSUE TITLE
API Logging not works.

### ISSUE THREAD

**Issue by jitendrar** [multidots/cakephp-rest-api#9]
I have created new file on config/api.php with below content.

`<?php

return [
    'ApiRequest' => [
        'debug' => true,
        'responseType' => 'json',
        'xmlResponseRootNode' => 'response',
        'responseFormat' => [
            'statusKey' => 'status',
            'statusOkText' => 'OK',
            'statusNokText' => 'NOK',
            'resultKey' => 'result',
            'messageKey' => 'message',
            'defaultMessageText' => 'Empty response!',
            'errorKey' => 'error',
            'defaultErrorText' => 'Unknown request!'
        ],
        'log' => true,
        'jwtAuth' => [
            'enabled' => true,
            'cypherKey' => 'R1a#2%dY2fX@3g8r5&s4Kf6*sd(5dHs!5gD4s',
            'tokenAlgorithm' => 'HS256'
        ],
        'cors' => [
            'enabled' => true,
            'origin' => '*',
            'allowedMethods' => ['POST', 'OPTIONS'],
            'allowedHeaders' => ['Content-Type, Authorization, Accept, Origin'],
            'maxAge' => 2628000
        ]
    ]
];`

Here, I have updated log value  to 'true'.  still it not logs anything in table.

**Comment by narendravaghela** [comment]
Hi @jitendrar 
Have you followed the database instructions from the readme file? You need a valid database table and your application must be able to connect to the database.
Please let me know if it still does not work.

**Comment by jitendrar** [comment]
Hi @narendravaghela 

I have followed same process as per readme file. I have created table in our database but it still not works.

**Comment by narendravaghela** [comment]
Hi @jitendrar 
Try to log the exception. Go to `/vendor/multidots/cakephp-rest-api/src/Utility/ApiRequestLogger.php` and place the log function in `catch` block.
```php
try {
//....
} catch (\Exception $e) {
    \Cake\Log\Log::debug($e->getMessage());
    return;
}
```
Check the debug.log file in your application.

**Comment by jitendrar** [comment]
Hi @narendravaghela 

Thanks for quick reply.

But my code is even not executing anything in /vendor/multidots/cakephp-rest-api/src/Utility/ApiRequestLogger.php file.

I have put your above code in catch but it not logging anything. I am thinking that I have did something wrong.

**Comment by narendravaghela** [comment]
Yup, try to debug your code and check what is going on.
Please share your results, so I can close the issue.

**Comment by jitendrar** [comment]
Hi, @narendravaghela 

I have already tried to debug code but no luck. After that I have added issue here so you can help to solve this.

If you have few minutes to look code then I can share that with you.

**Comment by narendravaghela** [comment]
Share your code. I will check it in my free time.

**Comment by jitendrar** [comment]
Route.php
------------

```
Router::prefix('scanner', function ($routes) {
    $routes->prefix('v1', function ($routes) {

        $routes->connect('/aa-scan-jobs', ['controller' => 'Foo', 'action' => 'bar', 'allowWithoutToken' => true, '_method' => 'GET']);

        $routes->connect('/aa-scannerconfig/:id', ['controller' => 'Foo', 'action' => 'barbar', 'allowWithoutToken' => true, '_method' => 'GET'], ['id' => '\d+', 'pass' => ['id']]);

        /*$routes->connect('/aa-alerts-master-vulnerability/:id', ['controller' => 'Foo', 'action' => 'barbaraaa', 'allowWithoutToken' => true, '_method' => 'POST'], ['id' => '\d+', 'pass' => ['id']]);*/

        //$routes->connect('aa-scan-jobs', ['controller' => 'Foo', 'action' => 'bar', 'allowWithoutToken' => true]);
    });
});
```

/config/api.php

```
<?php
return [
    'ApiRequest' => [
        'log' => true,
        // other config options
    ]
];
```
/src/Controller/scanner/V1/FooController.php

```
<?php

namespace App\Controller\Scanner\V1;

use Cake\Network\Exception\NotFoundException;
use RestApi\Controller\ApiController;
/**
 * Foo Controller
 */
class FooController extends ApiController
{

    public function initialize()
    {
        parent::initialize();
        //$this->loadComponent('Auth');
    }

    /**
     * bar method
     *
     */
    public function bar()
    {
        // Set the HTTP status code. By default, it is set to 200
        $this->httpStatusCode = 200;

       // movie list
        $movies = [
            'Captain America: Civil War',
            'The Wave',
            'Deadpool'
        ];

        $this->apiResponse['movies'] = $movies;
    }
```

These are the changes I have added in my code other than adding library in vendor folder.

Let me know if you need any further code for this.

Again thanks for your help.

**Comment by narendravaghela** [comment]
Are you able to access `/scanner/v1/aa-scan-jobs`?

**Comment by jitendrar** [comment]
yes.. I am able to access `/scanner/v1/aa-scan-jobs`

Below is what I am in response.

`{"status":"OK","result":{"movies":["Captain America: Civil War","The Wave","Deadpool"]}}`

**Comment by narendravaghela** [comment]
So for `/scanner/v1/aa-scan-jobs`, do you see any logs in the `api_requests` table in the database?

**Comment by jitendrar** [comment]
not single records added in api_requestes table.

**Comment by narendravaghela** [comment]
We will look into this issue.

**Comment by narendravaghela** [comment]
@jitendrar We tried installing a fresh version of CakePHP 3 and RestApi plugin, and it worked as expected.
Can you please recheck your installation and configuration?

**Comment by jitendrar** [comment]
@narendravaghela

I will try again fresh install and update you. If that will not work then will you help through TeamViewer?

**Comment by jitendrar** [comment]
@narendravaghela 

I have installed fresh CakePHP 3 and it is working fine.

I have found where the issue is. It is actually not working  because of my custom path of controller as per below.

`/src/Controller/scanner/V1/FooController.php`

Can you able to tell how to make it work for above path controller.

**Comment by narendravaghela** [comment]
It is about prefix routing. Read it more here - https://book.cakephp.org/3.0/en/development/routing.html#prefix-routing
Also, join the official slack channel and ask for help there - https://cakesf.slack.com/

**Comment by mikerogerz** [comment]
I ran into the same issue (using an /api prefix) and added a custom __invoke() method to extend the original middlewear.

https://gist.github.com/mikerogerz/db12fe9651500527b78b27adc5f306f5

**Comment by narendravaghela** [comment]
Interesting. I will surely check the prefix case.

**Comment by jitendrar** [comment]
@narendravaghela 

Any update on prefix case?

**Comment by mikerogerz** [comment]
Support was added in the latest commit. No further issues on my end.

**Comment by narendravaghela** [comment]
@jitendrar 
Please check the latest release, it has the fix for prefix routing.
